---
title: "Samanwoy Mukhopadhyay's resume"
author: Samanwoy Mukhopadhyay
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

Aside
==========================================================


Contact Info {#contact}
--------------------------------------------------------------------------------
- <i class="fa fa-user-circle" aria-hidden="true"></i>[Personal Website](https://samanwoy1989.github.io/)
- <i class="fa fa-envelope"></i> m.samanwoy@gmail.com
- <i class="fa fa-envelope-square"></i> sm3@nibmg.ac.in
- <i class="fa fa-github"></i> Github ID: [samanwoy1989](https://github.com/samanwoy1989)
- <i class="fa fa-phone"></i> +91 898-116-3530
- For more information, please contact me via email.
- [ORCiD ID](https://orcid.org/0000-0002-8660-5670
)
- <i class="fa fa-graduation-cap"></i> [Google Scholar](https://scholar.google.com/citations?user=hvi2rgQAAAAJ&hl=en&oi=sra)

Skills {#skills}
--------------------------------------------------------------------------------

- Experienced in Microarray, RNAseq, Single Cell RNAseq data analysis with bioconductor and R

- Skilled in R, LaTeX, Markdown, git
- Python and Bash literate
- Experienced in scientific computing with Linux OS 
- Experienced in website/API development

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.



Main
================================================================================

Samanwoy Mukhopadhyay {#title}
--------------------------------------------------------------------------------
<!-- **Currently searching for a post-doctoral researcher position in genomics** -->


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### University of Calcutta
B.Sc., Zoology (Honours) with 77.75% marks

2010

### University of Calcutta
M.Sc., Zoology, CGPA-8.56 with grade O (Outstanding) 

2012

### National Institute of Biomedical Genomics, Kalyani
Submitted Ph.D thesis in *Host Transcriptome Response in Sepsis*

2019

Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

- Experienced in transcriptomic data analysis, data mining, handling big data generated from the lab and also from the public domain.
- Experienced in performing meta-analysis from public data to draw inference from already available data in the field (GEO, TCGA).
- Experienced in creating data/ software packages (in R) for reproducibility of the work done.
- skilled in IDE such as Rstudio and Jupyter
- All the data and codes are available in public domain for each manuscript as a R vignette.
- Proficient in sweave, knitr, Markdown, Latex for scientific document writing.
- Skilled in Website/ API development through pagedown, blogdown, Shiny, distill, Markdown.
- Experienced in genomic data generation in a laboratory in Gene expression microarray. 
- Isolation of DNA, RNA from clinical samples, Bioanalyzer (capillary electrophoresis) for quality assessment of the nucleic acids, PCR, gel Electrophoresis, cDNA library preparation for gene expression microarray chips, gene expression microarray. 
- Literate in basic microbiological experiments. 
- Experienced lab management. From sample collection to data generation to data analysis and writing of reports. 
- Experienced to work in collaboration with technical staffs and other lab members to work as a team.

\newpage

Selected Publications {data-icon=file}
--------------------------------------------------------------------------------

###  Host response to SARS-CoV-2: Insight from transcriptomic studies. [<i class="fa fa-link"></i>](http://op.niscair.res.in/index.php/IJBB/article/view/42046)
**Mohapatra SK, Mukhopadhyay S**
**Indian Journal of Biochemistry and Biophysics (IJBB), 58(1), pp.7-12.** (**Review Article**)

2021

###  Dynamic dysregulation of IL-6 and genes functional in NETosis, complement and coagulation in severe COVID-19 illness. [<i class="fa fa-link"></i>](https://www.medrxiv.org/content/10.1101/2020.10.13.20211425v1) 
**medRxiv**. 2020 Oct 15. (**Pre-print**)  
**Mukhopadhyay S**, Sinha S, Mohapatra SK.

2020

### Sepsis-associated pathways segregate cancer groups. [<i class="fa fa-link"></i>](https://bmccancer.biomedcentral.com/articles/10.1186/s12885-020-06774-9) 
**BMC cancer**. 2020 Apr ;20:1-1. 
Tripathi H, **Mukhopadhyay S**, Mohapatra SK.

2020



###  Immunosuppression, rather than inflammation, is a salient feature of sepsis in an Indian cohort. [<i class="fa fa-link"></i>](https://www.biorxiv.org/content/10.1101/742924v1) 
**bioRxiv**. 2019 Aug 22:742924. (**Pre-print**)
**Mukhopadhyay S**, Thatoi PK, Das BK, Mohapatra SK.

2019


###  Transcriptomic meta-analysis reveals up-regulation of gene expression functional in osteoclast differentiation in human septic shock. [<i class="fa fa-link"></i>](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0171689) 
**PloS one**. 2017 Feb 15;12(2):e0171689.
**Mukhopadhyay S**, Thatoi PK, Pandey AD, Das BK, Ravindran B, Bhattacharjee S, Mohapatra SK.

2017

### Sepsis 2016 Agra: Pathway-level meta-analysis reveals transcriptional signature of septic shock. [<i class="fa fa-link"></i>](https://ccforum.biomedcentral.com/articles/10.1186/s13054-016-1204-x) 
**Critical Care (BMC)**. 2016;20(Suppl 1):5–6. (**Conference Paper**)
**Mukhopadhyay S**, Pandey AD, Bhattacharjee S, Mohapatra SK.

2016





Code and Data packages {data-icon=laptop}
--------------------------------------------
* Published Manuscript: Meta-analysis of Septic Shock: (R data package [<i class="fa fa-link"></i>](https://figshare.com/projects/ssnibmg/18664), Vignette[<i class="fa fa-link"></i>](https://figshare.com/projects/ssnibmg/18664))
* Published Manuscript: Sepsis-associated pathways segregate cancer groups
Rcode: [<i class="fa fa-link"></i>](https://figshare.com/articles/tcnibmgdoc/8118647/5,
https://figshare.com/articles/tcnibmgdoc/8118647/5)
Data-package [<i class="fa fa-link"></i>](https://figshare.com/articles/tcnibmg/8118413/3)
* Preprint: Host transcriptome analysis for survival of sepsis patients from an Indian cohort: (R data package [<i class="fa fa-link"></i>](https://figshare.com/projects/ssnibmgsurv/67721), Vignette
[<i class="fa fa-link"></i>](https://figshare.com/projects/ssnibmgsurv/67721))
* Preprint: Dynamic dysregulation of IL-6 and genes functional in NETosis, complement and coagulation in severe COVID-19 illness. [<i class="fa fa-link"></i>](https://github.com/samanwoy1989/covid-19)

Honors and Awards
------------------------------------

- Qualified: Joint Council for Scientific \& Industrial Research- University Grants Commission (CSIR-UGC) Test for Junior Research Fellowship and Eligibility for Lectureship (NET) held on 17-06-2012. Rank: 65/644 in Life Sciences.
- Post-Graduate Merit Scholarship (for university rank holders for PG Programs), University Grants Commission India (U.G.C.); 2010-2012.
- Sorashi Bala Choudury Memorial Scholarship (for university rank holders at graduation level), University of Calcutta, 2010.


    
Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------
- Participated as an instructor in "Introduction to R and analysing NGS data with R". Winter school on Analysing Genomic data, NIBMG 2017.
- Lab tour instructor in DNB workshop for population genetics, Feb. 2017, NIBMG.
- Participated as an instructor in "Introduction to R", NIBMG summer school for systems biology, July 2018.
- Participated as an instructor in NIBMG Clinical Genetics workshop, Dec,2019.

References
---------------------------------------------------

|  	|  	|  	|
|-	|-	|-	|
|  	|  	|  	|
| **Dr.Saroj Kant Mohapatra**<br>Assistant Professor<br>National Institute of<br>Biomedical Genomics<br>Kalyani 741251, India<br>email: skm1@nibmg.ac.in 	|  	| **Dr.Samsiddhi Bhattacharjee**<br>Associate Professor<br>National Institute of<br>Biomedical Genomics<br>Kalyani 741251, India<br>email:sb1@nibmg.ac.in 	|
|  	|  	|  	|
| **Dr.Analabha Basu**<br>Associate Professor<br>National Institute of<br>Biomedical Genomics<br>Kalyani 741251, India<br>email:ab1@nibmg.ac.in 	|  	| **Prof. Partha Pratim Majumder**<br>Distinguished Professor<br>National Institute of<br>Biomedical Genomics<br>Kalyani 741251, India<br>email:ppm1@nibmg.ac.in 	|


<!-- Dr.Saroj Kant Mohapatra -->
<!-- Assistant Professor -->
<!-- National Institute of -->
<!-- Biomedical Genomics -->
<!-- Kalyani 741251, India -->
<!-- email: skm1@nibmg.ac.in -->

<!-- Dr.Samsiddhi Bhattacharjee -->
<!-- Associate Professor -->
<!-- National Institute of -->
<!-- Biomedical Genomics -->
<!-- Kalyani 741251, India -->
<!-- email:sb1@nibmg.ac.in -->

<!-- Dr.Analabha Basu -->
<!-- Associate Professor -->
<!-- National Institute of -->
<!-- Biomedical Genomics -->
<!-- Kalyani 741251, India -->
<!-- email:ab1@nibmg.ac.in	 -->

<!-- Prof. Partha Pratim Majumder -->
<!-- Distinguished Professor -->
<!-- National Institute of -->
<!-- Biomedical Genomics -->
<!-- Kalyani 741251, India -->
<!-- email:ppm1@nibmg.ac.in -->
